package rv32i_pkg;

    //--------------------------------------------------
    // RV32I Opcodes (RISC-V ISA Specification)
    //--------------------------------------------------

    localparam logic [6:0] OPCODE_LUI      = 7'b0110111;
    localparam logic [6:0] OPCODE_AUIPC    = 7'b0010111;
    localparam logic [6:0] OPCODE_JAL      = 7'b1101111;
    localparam logic [6:0] OPCODE_JALR     = 7'b1100111;
    localparam logic [6:0] OPCODE_BRANCH   = 7'b1100011;
    localparam logic [6:0] OPCODE_LOAD     = 7'b0000011;
    localparam logic [6:0] OPCODE_STORE    = 7'b0100011;
    localparam logic [6:0] OPCODE_OP_IMM   = 7'b0010011;
    localparam logic [6:0] OPCODE_OP       = 7'b0110011;
    localparam logic [6:0] OPCODE_MISCMEM  = 7'b0001111;
    localparam logic [6:0] OPCODE_SYSTEM   = 7'b1110011;

    //--------------------------------------------------
    // ALU Operation Types
    // Generated by Main Control
    // Consumed by ALU Control
    //--------------------------------------------------

    localparam logic [1:0] ALUOP_ADD       = 2'b00;
    localparam logic [1:0] ALUOP_BRANCH    = 2'b01;
    localparam logic [1:0] ALUOP_RTYPE     = 2'b10;
    localparam logic [1:0] ALUOP_ITYPE     = 2'b11;

    //--------------------------------------------------
    // ALU Control Encoding
    // Generated by ALU Control
    // Consumed by ALU
    //--------------------------------------------------

    localparam logic [3:0] ALUCTRL_ADD     = 4'b0000;
    localparam logic [3:0] ALUCTRL_SUB     = 4'b0001;
    localparam logic [3:0] ALUCTRL_AND     = 4'b0010;
    localparam logic [3:0] ALUCTRL_OR      = 4'b0011;
    localparam logic [3:0] ALUCTRL_XOR     = 4'b0100;
    localparam logic [3:0] ALUCTRL_SLT     = 4'b0101;
    localparam logic [3:0] ALUCTRL_SLL     = 4'b0110;
    localparam logic [3:0] ALUCTRL_SRL     = 4'b0111;

endpackage
