/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module pipeline_datapath(clk, reset, debug_pc, debug_reg_write, debug_reg_addr, debug_reg_data);
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire [3:0] \alu_control_unit.alu_ctrl ;
  wire [1:0] \alu_control_unit.alu_op ;
  wire [2:0] \alu_control_unit.funct3 ;
  wire [6:0] \alu_control_unit.funct7 ;
  wire [3:0] alu_ctrl;
  wire [31:0] alu_input_a;
  wire [31:0] alu_input_b;
  wire [31:0] alu_input_b_forwarded;
  wire [1:0] alu_op;
  wire [31:0] alu_result;
  wire alu_src;
  wire [31:0] \alu_unit.a ;
  wire [3:0] \alu_unit.alu_ctrl ;
  wire [31:0] \alu_unit.b ;
  wire [31:0] \alu_unit.result ;
  wire branch;
  wire branch_taken;
  wire [31:0] branch_target;
  input clk;
  wire clk;
  wire [1:0] \control_unit.alu_op ;
  wire \control_unit.alu_src ;
  wire \control_unit.branch ;
  wire \control_unit.jump ;
  wire \control_unit.mem_read ;
  wire \control_unit.mem_to_reg ;
  wire \control_unit.mem_write ;
  wire [6:0] \control_unit.opcode ;
  wire \control_unit.reg_write ;
  wire \control_unit.wb_pc4 ;
  wire [31:0] \data_mem.address ;
  wire \data_mem.clk ;
  wire [31:0] \data_mem.i ;
  wire \data_mem.mem_read ;
  wire \data_mem.mem_write ;
  wire [31:0] \data_mem.memory[0] ;
  wire [31:0] \data_mem.memory[100] ;
  wire [31:0] \data_mem.memory[101] ;
  wire [31:0] \data_mem.memory[102] ;
  wire [31:0] \data_mem.memory[103] ;
  wire [31:0] \data_mem.memory[104] ;
  wire [31:0] \data_mem.memory[105] ;
  wire [31:0] \data_mem.memory[106] ;
  wire [31:0] \data_mem.memory[107] ;
  wire [31:0] \data_mem.memory[108] ;
  wire [31:0] \data_mem.memory[109] ;
  wire [31:0] \data_mem.memory[10] ;
  wire [31:0] \data_mem.memory[110] ;
  wire [31:0] \data_mem.memory[111] ;
  wire [31:0] \data_mem.memory[112] ;
  wire [31:0] \data_mem.memory[113] ;
  wire [31:0] \data_mem.memory[114] ;
  wire [31:0] \data_mem.memory[115] ;
  wire [31:0] \data_mem.memory[116] ;
  wire [31:0] \data_mem.memory[117] ;
  wire [31:0] \data_mem.memory[118] ;
  wire [31:0] \data_mem.memory[119] ;
  wire [31:0] \data_mem.memory[11] ;
  wire [31:0] \data_mem.memory[120] ;
  wire [31:0] \data_mem.memory[121] ;
  wire [31:0] \data_mem.memory[122] ;
  wire [31:0] \data_mem.memory[123] ;
  wire [31:0] \data_mem.memory[124] ;
  wire [31:0] \data_mem.memory[125] ;
  wire [31:0] \data_mem.memory[126] ;
  wire [31:0] \data_mem.memory[127] ;
  wire [31:0] \data_mem.memory[128] ;
  wire [31:0] \data_mem.memory[129] ;
  wire [31:0] \data_mem.memory[12] ;
  wire [31:0] \data_mem.memory[130] ;
  wire [31:0] \data_mem.memory[131] ;
  wire [31:0] \data_mem.memory[132] ;
  wire [31:0] \data_mem.memory[133] ;
  wire [31:0] \data_mem.memory[134] ;
  wire [31:0] \data_mem.memory[135] ;
  wire [31:0] \data_mem.memory[136] ;
  wire [31:0] \data_mem.memory[137] ;
  wire [31:0] \data_mem.memory[138] ;
  wire [31:0] \data_mem.memory[139] ;
  wire [31:0] \data_mem.memory[13] ;
  wire [31:0] \data_mem.memory[140] ;
  wire [31:0] \data_mem.memory[141] ;
  wire [31:0] \data_mem.memory[142] ;
  wire [31:0] \data_mem.memory[143] ;
  wire [31:0] \data_mem.memory[144] ;
  wire [31:0] \data_mem.memory[145] ;
  wire [31:0] \data_mem.memory[146] ;
  wire [31:0] \data_mem.memory[147] ;
  wire [31:0] \data_mem.memory[148] ;
  wire [31:0] \data_mem.memory[149] ;
  wire [31:0] \data_mem.memory[14] ;
  wire [31:0] \data_mem.memory[150] ;
  wire [31:0] \data_mem.memory[151] ;
  wire [31:0] \data_mem.memory[152] ;
  wire [31:0] \data_mem.memory[153] ;
  wire [31:0] \data_mem.memory[154] ;
  wire [31:0] \data_mem.memory[155] ;
  wire [31:0] \data_mem.memory[156] ;
  wire [31:0] \data_mem.memory[157] ;
  wire [31:0] \data_mem.memory[158] ;
  wire [31:0] \data_mem.memory[159] ;
  wire [31:0] \data_mem.memory[15] ;
  wire [31:0] \data_mem.memory[160] ;
  wire [31:0] \data_mem.memory[161] ;
  wire [31:0] \data_mem.memory[162] ;
  wire [31:0] \data_mem.memory[163] ;
  wire [31:0] \data_mem.memory[164] ;
  wire [31:0] \data_mem.memory[165] ;
  wire [31:0] \data_mem.memory[166] ;
  wire [31:0] \data_mem.memory[167] ;
  wire [31:0] \data_mem.memory[168] ;
  wire [31:0] \data_mem.memory[169] ;
  wire [31:0] \data_mem.memory[16] ;
  wire [31:0] \data_mem.memory[170] ;
  wire [31:0] \data_mem.memory[171] ;
  wire [31:0] \data_mem.memory[172] ;
  wire [31:0] \data_mem.memory[173] ;
  wire [31:0] \data_mem.memory[174] ;
  wire [31:0] \data_mem.memory[175] ;
  wire [31:0] \data_mem.memory[176] ;
  wire [31:0] \data_mem.memory[177] ;
  wire [31:0] \data_mem.memory[178] ;
  wire [31:0] \data_mem.memory[179] ;
  wire [31:0] \data_mem.memory[17] ;
  wire [31:0] \data_mem.memory[180] ;
  wire [31:0] \data_mem.memory[181] ;
  wire [31:0] \data_mem.memory[182] ;
  wire [31:0] \data_mem.memory[183] ;
  wire [31:0] \data_mem.memory[184] ;
  wire [31:0] \data_mem.memory[185] ;
  wire [31:0] \data_mem.memory[186] ;
  wire [31:0] \data_mem.memory[187] ;
  wire [31:0] \data_mem.memory[188] ;
  wire [31:0] \data_mem.memory[189] ;
  wire [31:0] \data_mem.memory[18] ;
  wire [31:0] \data_mem.memory[190] ;
  wire [31:0] \data_mem.memory[191] ;
  wire [31:0] \data_mem.memory[192] ;
  wire [31:0] \data_mem.memory[193] ;
  wire [31:0] \data_mem.memory[194] ;
  wire [31:0] \data_mem.memory[195] ;
  wire [31:0] \data_mem.memory[196] ;
  wire [31:0] \data_mem.memory[197] ;
  wire [31:0] \data_mem.memory[198] ;
  wire [31:0] \data_mem.memory[199] ;
  wire [31:0] \data_mem.memory[19] ;
  wire [31:0] \data_mem.memory[1] ;
  wire [31:0] \data_mem.memory[200] ;
  wire [31:0] \data_mem.memory[201] ;
  wire [31:0] \data_mem.memory[202] ;
  wire [31:0] \data_mem.memory[203] ;
  wire [31:0] \data_mem.memory[204] ;
  wire [31:0] \data_mem.memory[205] ;
  wire [31:0] \data_mem.memory[206] ;
  wire [31:0] \data_mem.memory[207] ;
  wire [31:0] \data_mem.memory[208] ;
  wire [31:0] \data_mem.memory[209] ;
  wire [31:0] \data_mem.memory[20] ;
  wire [31:0] \data_mem.memory[210] ;
  wire [31:0] \data_mem.memory[211] ;
  wire [31:0] \data_mem.memory[212] ;
  wire [31:0] \data_mem.memory[213] ;
  wire [31:0] \data_mem.memory[214] ;
  wire [31:0] \data_mem.memory[215] ;
  wire [31:0] \data_mem.memory[216] ;
  wire [31:0] \data_mem.memory[217] ;
  wire [31:0] \data_mem.memory[218] ;
  wire [31:0] \data_mem.memory[219] ;
  wire [31:0] \data_mem.memory[21] ;
  wire [31:0] \data_mem.memory[220] ;
  wire [31:0] \data_mem.memory[221] ;
  wire [31:0] \data_mem.memory[222] ;
  wire [31:0] \data_mem.memory[223] ;
  wire [31:0] \data_mem.memory[224] ;
  wire [31:0] \data_mem.memory[225] ;
  wire [31:0] \data_mem.memory[226] ;
  wire [31:0] \data_mem.memory[227] ;
  wire [31:0] \data_mem.memory[228] ;
  wire [31:0] \data_mem.memory[229] ;
  wire [31:0] \data_mem.memory[22] ;
  wire [31:0] \data_mem.memory[230] ;
  wire [31:0] \data_mem.memory[231] ;
  wire [31:0] \data_mem.memory[232] ;
  wire [31:0] \data_mem.memory[233] ;
  wire [31:0] \data_mem.memory[234] ;
  wire [31:0] \data_mem.memory[235] ;
  wire [31:0] \data_mem.memory[236] ;
  wire [31:0] \data_mem.memory[237] ;
  wire [31:0] \data_mem.memory[238] ;
  wire [31:0] \data_mem.memory[239] ;
  wire [31:0] \data_mem.memory[23] ;
  wire [31:0] \data_mem.memory[240] ;
  wire [31:0] \data_mem.memory[241] ;
  wire [31:0] \data_mem.memory[242] ;
  wire [31:0] \data_mem.memory[243] ;
  wire [31:0] \data_mem.memory[244] ;
  wire [31:0] \data_mem.memory[245] ;
  wire [31:0] \data_mem.memory[246] ;
  wire [31:0] \data_mem.memory[247] ;
  wire [31:0] \data_mem.memory[248] ;
  wire [31:0] \data_mem.memory[249] ;
  wire [31:0] \data_mem.memory[24] ;
  wire [31:0] \data_mem.memory[250] ;
  wire [31:0] \data_mem.memory[251] ;
  wire [31:0] \data_mem.memory[252] ;
  wire [31:0] \data_mem.memory[253] ;
  wire [31:0] \data_mem.memory[254] ;
  wire [31:0] \data_mem.memory[255] ;
  wire [31:0] \data_mem.memory[25] ;
  wire [31:0] \data_mem.memory[26] ;
  wire [31:0] \data_mem.memory[27] ;
  wire [31:0] \data_mem.memory[28] ;
  wire [31:0] \data_mem.memory[29] ;
  wire [31:0] \data_mem.memory[2] ;
  wire [31:0] \data_mem.memory[30] ;
  wire [31:0] \data_mem.memory[31] ;
  wire [31:0] \data_mem.memory[32] ;
  wire [31:0] \data_mem.memory[33] ;
  wire [31:0] \data_mem.memory[34] ;
  wire [31:0] \data_mem.memory[35] ;
  wire [31:0] \data_mem.memory[36] ;
  wire [31:0] \data_mem.memory[37] ;
  wire [31:0] \data_mem.memory[38] ;
  wire [31:0] \data_mem.memory[39] ;
  wire [31:0] \data_mem.memory[3] ;
  wire [31:0] \data_mem.memory[40] ;
  wire [31:0] \data_mem.memory[41] ;
  wire [31:0] \data_mem.memory[42] ;
  wire [31:0] \data_mem.memory[43] ;
  wire [31:0] \data_mem.memory[44] ;
  wire [31:0] \data_mem.memory[45] ;
  wire [31:0] \data_mem.memory[46] ;
  wire [31:0] \data_mem.memory[47] ;
  wire [31:0] \data_mem.memory[48] ;
  wire [31:0] \data_mem.memory[49] ;
  wire [31:0] \data_mem.memory[4] ;
  wire [31:0] \data_mem.memory[50] ;
  wire [31:0] \data_mem.memory[51] ;
  wire [31:0] \data_mem.memory[52] ;
  wire [31:0] \data_mem.memory[53] ;
  wire [31:0] \data_mem.memory[54] ;
  wire [31:0] \data_mem.memory[55] ;
  wire [31:0] \data_mem.memory[56] ;
  wire [31:0] \data_mem.memory[57] ;
  wire [31:0] \data_mem.memory[58] ;
  wire [31:0] \data_mem.memory[59] ;
  wire [31:0] \data_mem.memory[5] ;
  wire [31:0] \data_mem.memory[60] ;
  wire [31:0] \data_mem.memory[61] ;
  wire [31:0] \data_mem.memory[62] ;
  wire [31:0] \data_mem.memory[63] ;
  wire [31:0] \data_mem.memory[64] ;
  wire [31:0] \data_mem.memory[65] ;
  wire [31:0] \data_mem.memory[66] ;
  wire [31:0] \data_mem.memory[67] ;
  wire [31:0] \data_mem.memory[68] ;
  wire [31:0] \data_mem.memory[69] ;
  wire [31:0] \data_mem.memory[6] ;
  wire [31:0] \data_mem.memory[70] ;
  wire [31:0] \data_mem.memory[71] ;
  wire [31:0] \data_mem.memory[72] ;
  wire [31:0] \data_mem.memory[73] ;
  wire [31:0] \data_mem.memory[74] ;
  wire [31:0] \data_mem.memory[75] ;
  wire [31:0] \data_mem.memory[76] ;
  wire [31:0] \data_mem.memory[77] ;
  wire [31:0] \data_mem.memory[78] ;
  wire [31:0] \data_mem.memory[79] ;
  wire [31:0] \data_mem.memory[7] ;
  wire [31:0] \data_mem.memory[80] ;
  wire [31:0] \data_mem.memory[81] ;
  wire [31:0] \data_mem.memory[82] ;
  wire [31:0] \data_mem.memory[83] ;
  wire [31:0] \data_mem.memory[84] ;
  wire [31:0] \data_mem.memory[85] ;
  wire [31:0] \data_mem.memory[86] ;
  wire [31:0] \data_mem.memory[87] ;
  wire [31:0] \data_mem.memory[88] ;
  wire [31:0] \data_mem.memory[89] ;
  wire [31:0] \data_mem.memory[8] ;
  wire [31:0] \data_mem.memory[90] ;
  wire [31:0] \data_mem.memory[91] ;
  wire [31:0] \data_mem.memory[92] ;
  wire [31:0] \data_mem.memory[93] ;
  wire [31:0] \data_mem.memory[94] ;
  wire [31:0] \data_mem.memory[95] ;
  wire [31:0] \data_mem.memory[96] ;
  wire [31:0] \data_mem.memory[97] ;
  wire [31:0] \data_mem.memory[98] ;
  wire [31:0] \data_mem.memory[99] ;
  wire [31:0] \data_mem.memory[9] ;
  wire [31:0] \data_mem.write_data ;
  output [31:0] debug_pc;
  wire [31:0] debug_pc;
  output [4:0] debug_reg_addr;
  wire [4:0] debug_reg_addr;
  output [31:0] debug_reg_data;
  wire [31:0] debug_reg_data;
  output debug_reg_write;
  wire debug_reg_write;
  wire [2:0] \decoder_unit.funct3 ;
  wire [6:0] \decoder_unit.funct7 ;
  wire [31:0] \decoder_unit.instruction ;
  wire [6:0] \decoder_unit.opcode ;
  wire [4:0] \decoder_unit.rd ;
  wire [4:0] \decoder_unit.rs1 ;
  wire [4:0] \decoder_unit.rs2 ;
  wire [31:0] ex_mem_alu_result;
  wire ex_mem_mem_read;
  wire ex_mem_mem_to_reg;
  wire ex_mem_mem_write;
  wire [31:0] ex_mem_pc_plus4;
  wire [4:0] ex_mem_rd;
  wire [31:0] \ex_mem_reg.alu_result_in ;
  wire [31:0] \ex_mem_reg.alu_result_out ;
  wire \ex_mem_reg.branch_in ;
  wire \ex_mem_reg.clk ;
  wire \ex_mem_reg.jump_in ;
  wire \ex_mem_reg.mem_read_in ;
  wire \ex_mem_reg.mem_read_out ;
  wire \ex_mem_reg.mem_to_reg_in ;
  wire \ex_mem_reg.mem_to_reg_out ;
  wire \ex_mem_reg.mem_write_in ;
  wire \ex_mem_reg.mem_write_out ;
  wire [31:0] \ex_mem_reg.pc_plus4_in ;
  wire [31:0] \ex_mem_reg.pc_plus4_out ;
  wire [4:0] \ex_mem_reg.rd_in ;
  wire [4:0] \ex_mem_reg.rd_out ;
  wire \ex_mem_reg.reg_write_in ;
  wire \ex_mem_reg.reg_write_out ;
  wire \ex_mem_reg.reset ;
  wire \ex_mem_reg.wb_pc4_in ;
  wire \ex_mem_reg.wb_pc4_out ;
  wire [31:0] \ex_mem_reg.write_data_in ;
  wire [31:0] \ex_mem_reg.write_data_out ;
  wire ex_mem_reg_write;
  wire [31:0] ex_mem_rs2_data;
  wire ex_mem_wb_pc4;
  wire [1:0] forward_a;
  wire [1:0] forward_b;
  wire [4:0] \forwarding_unit_inst.ex_mem_rd ;
  wire \forwarding_unit_inst.ex_mem_reg_write ;
  wire [1:0] \forwarding_unit_inst.forward_a ;
  wire [1:0] \forwarding_unit_inst.forward_b ;
  wire [4:0] \forwarding_unit_inst.id_ex_rs1 ;
  wire [4:0] \forwarding_unit_inst.id_ex_rs2 ;
  wire [4:0] \forwarding_unit_inst.mem_wb_rd ;
  wire \forwarding_unit_inst.mem_wb_reg_write ;
  wire [2:0] funct3;
  wire [6:0] funct7;
  wire \hazard_unit.control_mux_select ;
  wire \hazard_unit.id_ex_memread ;
  wire [4:0] \hazard_unit.id_ex_rd ;
  wire [4:0] \hazard_unit.if_id_rs1 ;
  wire [4:0] \hazard_unit.if_id_rs2 ;
  wire \hazard_unit.if_id_write ;
  wire \hazard_unit.pc_write ;
  wire [1:0] id_ex_alu_op;
  wire id_ex_alu_src;
  wire id_ex_branch;
  wire id_ex_branch_flush;
  wire id_ex_flush;
  wire [2:0] id_ex_funct3;
  wire [6:0] id_ex_funct7;
  wire [31:0] id_ex_imm;
  wire id_ex_jump;
  wire id_ex_mem_read;
  wire id_ex_mem_to_reg;
  wire id_ex_mem_write;
  wire [6:0] id_ex_opcode;
  wire [31:0] id_ex_pc;
  wire [4:0] id_ex_rd;
  wire [1:0] \id_ex_reg.alu_op_in ;
  wire [1:0] \id_ex_reg.alu_op_out ;
  wire \id_ex_reg.alu_src_in ;
  wire \id_ex_reg.alu_src_out ;
  wire \id_ex_reg.branch_in ;
  wire \id_ex_reg.branch_out ;
  wire \id_ex_reg.clk ;
  wire [2:0] \id_ex_reg.funct3_in ;
  wire [2:0] \id_ex_reg.funct3_out ;
  wire [6:0] \id_ex_reg.funct7_in ;
  wire [6:0] \id_ex_reg.funct7_out ;
  wire [31:0] \id_ex_reg.imm_in ;
  wire [31:0] \id_ex_reg.imm_out ;
  wire \id_ex_reg.jump_in ;
  wire \id_ex_reg.jump_out ;
  wire \id_ex_reg.mem_read_in ;
  wire \id_ex_reg.mem_read_out ;
  wire \id_ex_reg.mem_to_reg_in ;
  wire \id_ex_reg.mem_to_reg_out ;
  wire \id_ex_reg.mem_write_in ;
  wire \id_ex_reg.mem_write_out ;
  wire [6:0] \id_ex_reg.opcode_in ;
  wire [6:0] \id_ex_reg.opcode_out ;
  wire [31:0] \id_ex_reg.pc_in ;
  wire [31:0] \id_ex_reg.pc_out ;
  wire [4:0] \id_ex_reg.rd_in ;
  wire [4:0] \id_ex_reg.rd_out ;
  wire \id_ex_reg.reg_write_in ;
  wire \id_ex_reg.reg_write_out ;
  wire \id_ex_reg.reset ;
  wire [31:0] \id_ex_reg.rs1_data_in ;
  wire [31:0] \id_ex_reg.rs1_data_out ;
  wire [4:0] \id_ex_reg.rs1_in ;
  wire [4:0] \id_ex_reg.rs1_out ;
  wire [31:0] \id_ex_reg.rs2_data_in ;
  wire [31:0] \id_ex_reg.rs2_data_out ;
  wire [4:0] \id_ex_reg.rs2_in ;
  wire [4:0] \id_ex_reg.rs2_out ;
  wire \id_ex_reg.wb_pc4_in ;
  wire \id_ex_reg.wb_pc4_out ;
  wire id_ex_reg_write;
  wire [4:0] id_ex_rs1;
  wire [31:0] id_ex_rs1_data;
  wire [4:0] id_ex_rs2;
  wire [31:0] id_ex_rs2_data;
  wire id_ex_wb_pc4;
  wire if_id_flush;
  wire [31:0] if_id_instruction;
  wire [31:0] if_id_pc;
  wire \if_id_reg.clk ;
  wire \if_id_reg.flush ;
  wire [31:0] \if_id_reg.instruction_in ;
  wire [31:0] \if_id_reg.instruction_out ;
  wire [31:0] \if_id_reg.pc_in ;
  wire [31:0] \if_id_reg.pc_out ;
  wire \if_id_reg.reset ;
  wire \if_id_reg.write_enable ;
  wire if_id_write;
  wire [31:0] \imem.address ;
  wire [31:0] \imem.instruction ;
  wire [31:0] imm_out;
  wire [31:0] \imm_unit.imm_out ;
  wire [31:0] \imm_unit.instruction ;
  wire [31:0] instruction;
  wire [31:0] jalr_target;
  wire jump;
  wire jump_taken;
  wire [31:0] jump_target;
  wire mem_read;
  wire mem_to_reg;
  wire [31:0] mem_wb_alu_result;
  wire [31:0] mem_wb_mem_data;
  wire mem_wb_mem_to_reg;
  wire [31:0] mem_wb_pc_plus4;
  wire [4:0] mem_wb_rd;
  wire [31:0] \mem_wb_reg.alu_result_in ;
  wire [31:0] \mem_wb_reg.alu_result_out ;
  wire \mem_wb_reg.clk ;
  wire [31:0] \mem_wb_reg.mem_data_out ;
  wire \mem_wb_reg.mem_to_reg_in ;
  wire \mem_wb_reg.mem_to_reg_out ;
  wire [31:0] \mem_wb_reg.pc_plus4_in ;
  wire [31:0] \mem_wb_reg.pc_plus4_out ;
  wire [4:0] \mem_wb_reg.rd_in ;
  wire [4:0] \mem_wb_reg.rd_out ;
  wire \mem_wb_reg.reg_write_in ;
  wire \mem_wb_reg.reg_write_out ;
  wire \mem_wb_reg.reset ;
  wire \mem_wb_reg.wb_pc4_in ;
  wire \mem_wb_reg.wb_pc4_out ;
  wire mem_wb_reg_write;
  wire mem_wb_wb_pc4;
  wire mem_write;
  wire [31:0] next_pc;
  wire [6:0] opcode;
  wire [31:0] pc_plus4;
  wire \pc_unit.clk ;
  wire [31:0] \pc_unit.next_pc ;
  wire [31:0] \pc_unit.pc ;
  wire \pc_unit.pc_write ;
  wire \pc_unit.reset ;
  wire [31:0] pc_value;
  wire pc_write;
  wire [4:0] rd;
  wire reg_write;
  wire \regfile_unit.clk ;
  wire [31:0] \regfile_unit.i ;
  wire [4:0] \regfile_unit.rd_addr ;
  wire [31:0] \regfile_unit.rd_data ;
  wire \regfile_unit.reg_write ;
  wire [31:0] \regfile_unit.regfile[10] ;
  wire [31:0] \regfile_unit.regfile[11] ;
  wire [31:0] \regfile_unit.regfile[12] ;
  wire [31:0] \regfile_unit.regfile[13] ;
  wire [31:0] \regfile_unit.regfile[14] ;
  wire [31:0] \regfile_unit.regfile[15] ;
  wire [31:0] \regfile_unit.regfile[16] ;
  wire [31:0] \regfile_unit.regfile[17] ;
  wire [31:0] \regfile_unit.regfile[18] ;
  wire [31:0] \regfile_unit.regfile[19] ;
  wire [31:0] \regfile_unit.regfile[1] ;
  wire [31:0] \regfile_unit.regfile[20] ;
  wire [31:0] \regfile_unit.regfile[21] ;
  wire [31:0] \regfile_unit.regfile[22] ;
  wire [31:0] \regfile_unit.regfile[23] ;
  wire [31:0] \regfile_unit.regfile[24] ;
  wire [31:0] \regfile_unit.regfile[25] ;
  wire [31:0] \regfile_unit.regfile[26] ;
  wire [31:0] \regfile_unit.regfile[27] ;
  wire [31:0] \regfile_unit.regfile[28] ;
  wire [31:0] \regfile_unit.regfile[29] ;
  wire [31:0] \regfile_unit.regfile[2] ;
  wire [31:0] \regfile_unit.regfile[30] ;
  wire [31:0] \regfile_unit.regfile[3] ;
  wire [31:0] \regfile_unit.regfile[4] ;
  wire [31:0] \regfile_unit.regfile[5] ;
  wire [31:0] \regfile_unit.regfile[6] ;
  wire [31:0] \regfile_unit.regfile[7] ;
  wire [31:0] \regfile_unit.regfile[8] ;
  wire [31:0] \regfile_unit.regfile[9] ;
  wire [4:0] \regfile_unit.rs1_addr ;
  wire [31:0] \regfile_unit.rs1_data ;
  wire [4:0] \regfile_unit.rs2_addr ;
  wire [31:0] \regfile_unit.rs2_data ;
  input reset;
  wire reset;
  wire [4:0] rs1;
  wire [31:0] rs1_data;
  wire [4:0] rs2;
  wire [31:0] rs2_data;
  wire [31:0] store_data_forwarded;
  wire wb_pc4;
  wire [31:0] writeback_data;
  sky130_fd_sc_hd__clkinv_1 _241_ (
    .A(reset),
    .Y(_218_)
  );
  sky130_fd_sc_hd__clkinv_1 _242_ (
    .A(\pc_unit.pc [2]),
    .Y(\pc_unit.next_pc [2])
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(\pc_unit.pc [9]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__clkinv_1 _244_ (
    .A(\pc_unit.pc [10]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__clkinv_1 _245_ (
    .A(\pc_unit.pc [11]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(\pc_unit.pc [15]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__clkinv_1 _247_ (
    .A(\pc_unit.pc [16]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__clkinv_1 _248_ (
    .A(\pc_unit.pc [17]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _249_ (
    .A(\pc_unit.pc [21]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__clkinv_1 _250_ (
    .A(\pc_unit.pc [22]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__clkinv_1 _251_ (
    .A(\pc_unit.pc [23]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(\pc_unit.pc [2]),
    .B(\pc_unit.pc [3]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__xor2_1 _253_ (
    .A(\pc_unit.pc [2]),
    .B(\pc_unit.pc [3]),
    .X(\pc_unit.next_pc [3])
  );
  sky130_fd_sc_hd__xnor2_1 _254_ (
    .A(\pc_unit.pc [4]),
    .B(_130_),
    .Y(\pc_unit.next_pc [4])
  );
  sky130_fd_sc_hd__and4_1 _255_ (
    .A(\pc_unit.pc [2]),
    .B(\pc_unit.pc [3]),
    .C(\pc_unit.pc [4]),
    .D(\pc_unit.pc [5]),
    .X(_131_)
  );
  sky130_fd_sc_hd__a31oi_1 _256_ (
    .A1(\pc_unit.pc [2]),
    .A2(\pc_unit.pc [3]),
    .A3(\pc_unit.pc [4]),
    .B1(\pc_unit.pc [5]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(_131_),
    .B(_132_),
    .Y(\pc_unit.next_pc [5])
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(\pc_unit.pc [6]),
    .B(_131_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__xor2_1 _259_ (
    .A(\pc_unit.pc [6]),
    .B(_131_),
    .X(\pc_unit.next_pc [6])
  );
  sky130_fd_sc_hd__xnor2_1 _260_ (
    .A(\pc_unit.pc [7]),
    .B(_133_),
    .Y(\pc_unit.next_pc [7])
  );
  sky130_fd_sc_hd__nand4_1 _261_ (
    .A(\pc_unit.pc [6]),
    .B(\pc_unit.pc [7]),
    .C(\pc_unit.pc [8]),
    .D(_131_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a31oi_1 _262_ (
    .A1(\pc_unit.pc [6]),
    .A2(\pc_unit.pc [7]),
    .A3(_131_),
    .B1(\pc_unit.pc [8]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _263_ (
    .A(_134_),
    .SLEEP(_135_),
    .X(\pc_unit.next_pc [8])
  );
  sky130_fd_sc_hd__nor2_1 _264_ (
    .A(_121_),
    .B(_134_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _265_ (
    .A(\pc_unit.pc [9]),
    .B(_134_),
    .Y(\pc_unit.next_pc [9])
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(_122_),
    .B(_136_),
    .Y(\pc_unit.next_pc [10])
  );
  sky130_fd_sc_hd__nor4_1 _267_ (
    .A(_121_),
    .B(_122_),
    .C(_123_),
    .D(_134_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _268_ (
    .A1(\pc_unit.pc [10]),
    .A2(_136_),
    .B1(\pc_unit.pc [11]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _269_ (
    .A(_137_),
    .B(_138_),
    .Y(\pc_unit.next_pc [11])
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(\pc_unit.pc [12]),
    .B(_137_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__xor2_1 _271_ (
    .A(\pc_unit.pc [12]),
    .B(_137_),
    .X(\pc_unit.next_pc [12])
  );
  sky130_fd_sc_hd__xnor2_1 _272_ (
    .A(\pc_unit.pc [13]),
    .B(_139_),
    .Y(\pc_unit.next_pc [13])
  );
  sky130_fd_sc_hd__nand4_1 _273_ (
    .A(\pc_unit.pc [12]),
    .B(\pc_unit.pc [13]),
    .C(\pc_unit.pc [14]),
    .D(_137_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a31oi_1 _274_ (
    .A1(\pc_unit.pc [12]),
    .A2(\pc_unit.pc [13]),
    .A3(_137_),
    .B1(\pc_unit.pc [14]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _275_ (
    .A(_140_),
    .SLEEP(_141_),
    .X(\pc_unit.next_pc [14])
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(_124_),
    .B(_140_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__xnor2_1 _277_ (
    .A(\pc_unit.pc [15]),
    .B(_140_),
    .Y(\pc_unit.next_pc [15])
  );
  sky130_fd_sc_hd__xnor2_1 _278_ (
    .A(_125_),
    .B(_142_),
    .Y(\pc_unit.next_pc [16])
  );
  sky130_fd_sc_hd__nor4_1 _279_ (
    .A(_124_),
    .B(_125_),
    .C(_126_),
    .D(_140_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21oi_1 _280_ (
    .A1(\pc_unit.pc [16]),
    .A2(_142_),
    .B1(\pc_unit.pc [17]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _281_ (
    .A(_143_),
    .B(_144_),
    .Y(\pc_unit.next_pc [17])
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(\pc_unit.pc [18]),
    .B(_143_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__xor2_1 _283_ (
    .A(\pc_unit.pc [18]),
    .B(_143_),
    .X(\pc_unit.next_pc [18])
  );
  sky130_fd_sc_hd__xnor2_1 _284_ (
    .A(\pc_unit.pc [19]),
    .B(_145_),
    .Y(\pc_unit.next_pc [19])
  );
  sky130_fd_sc_hd__nand4_1 _285_ (
    .A(\pc_unit.pc [18]),
    .B(\pc_unit.pc [19]),
    .C(\pc_unit.pc [20]),
    .D(_143_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a31oi_1 _286_ (
    .A1(\pc_unit.pc [18]),
    .A2(\pc_unit.pc [19]),
    .A3(_143_),
    .B1(\pc_unit.pc [20]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _287_ (
    .A(_146_),
    .SLEEP(_147_),
    .X(\pc_unit.next_pc [20])
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(_127_),
    .B(_146_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__xnor2_1 _289_ (
    .A(\pc_unit.pc [21]),
    .B(_146_),
    .Y(\pc_unit.next_pc [21])
  );
  sky130_fd_sc_hd__xnor2_1 _290_ (
    .A(_128_),
    .B(_148_),
    .Y(\pc_unit.next_pc [22])
  );
  sky130_fd_sc_hd__nor4_1 _291_ (
    .A(_127_),
    .B(_128_),
    .C(_129_),
    .D(_146_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _292_ (
    .A1(\pc_unit.pc [22]),
    .A2(_148_),
    .B1(\pc_unit.pc [23]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_149_),
    .B(_150_),
    .Y(\pc_unit.next_pc [23])
  );
  sky130_fd_sc_hd__and2_0 _294_ (
    .A(\pc_unit.pc [24]),
    .B(_149_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nor2_1 _295_ (
    .A(\pc_unit.pc [24]),
    .B(_149_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _296_ (
    .A(_151_),
    .B(_152_),
    .Y(\pc_unit.next_pc [24])
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(\pc_unit.pc [25]),
    .B(_151_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xor2_1 _298_ (
    .A(\pc_unit.pc [25]),
    .B(_151_),
    .X(\pc_unit.next_pc [25])
  );
  sky130_fd_sc_hd__nand4_1 _299_ (
    .A(\pc_unit.pc [24]),
    .B(\pc_unit.pc [25]),
    .C(\pc_unit.pc [26]),
    .D(_149_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__xnor2_1 _300_ (
    .A(\pc_unit.pc [26]),
    .B(_153_),
    .Y(\pc_unit.next_pc [26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _301_ (
    .A(\pc_unit.pc [27]),
    .SLEEP(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd__xnor2_1 _302_ (
    .A(\pc_unit.pc [27]),
    .B(_154_),
    .Y(\pc_unit.next_pc [27])
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(\pc_unit.pc [28]),
    .B(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__xor2_1 _304_ (
    .A(\pc_unit.pc [28]),
    .B(_155_),
    .X(\pc_unit.next_pc [28])
  );
  sky130_fd_sc_hd__xnor2_1 _305_ (
    .A(\pc_unit.pc [29]),
    .B(_156_),
    .Y(\pc_unit.next_pc [29])
  );
  sky130_fd_sc_hd__nand4_1 _306_ (
    .A(\pc_unit.pc [28]),
    .B(\pc_unit.pc [29]),
    .C(\pc_unit.pc [30]),
    .D(_155_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a31oi_1 _307_ (
    .A1(\pc_unit.pc [28]),
    .A2(\pc_unit.pc [29]),
    .A3(_155_),
    .B1(\pc_unit.pc [30]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _308_ (
    .A(_157_),
    .SLEEP(_158_),
    .X(\pc_unit.next_pc [30])
  );
  sky130_fd_sc_hd__xnor2_1 _309_ (
    .A(\pc_unit.pc [31]),
    .B(_157_),
    .Y(\pc_unit.next_pc [31])
  );
  sky130_fd_sc_hd__clkinv_1 _310_ (
    .A(reset),
    .Y(_217_)
  );
  sky130_fd_sc_hd__clkinv_1 _311_ (
    .A(reset),
    .Y(_216_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(reset),
    .Y(_215_)
  );
  sky130_fd_sc_hd__clkinv_1 _313_ (
    .A(reset),
    .Y(_214_)
  );
  sky130_fd_sc_hd__clkinv_1 _314_ (
    .A(reset),
    .Y(_213_)
  );
  sky130_fd_sc_hd__clkinv_1 _315_ (
    .A(reset),
    .Y(_212_)
  );
  sky130_fd_sc_hd__clkinv_1 _316_ (
    .A(reset),
    .Y(_211_)
  );
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(reset),
    .Y(_210_)
  );
  sky130_fd_sc_hd__clkinv_1 _318_ (
    .A(reset),
    .Y(_209_)
  );
  sky130_fd_sc_hd__clkinv_1 _319_ (
    .A(reset),
    .Y(_208_)
  );
  sky130_fd_sc_hd__clkinv_1 _320_ (
    .A(reset),
    .Y(_207_)
  );
  sky130_fd_sc_hd__clkinv_1 _321_ (
    .A(reset),
    .Y(_206_)
  );
  sky130_fd_sc_hd__clkinv_1 _322_ (
    .A(reset),
    .Y(_205_)
  );
  sky130_fd_sc_hd__clkinv_1 _323_ (
    .A(reset),
    .Y(_204_)
  );
  sky130_fd_sc_hd__clkinv_1 _324_ (
    .A(reset),
    .Y(_203_)
  );
  sky130_fd_sc_hd__clkinv_1 _325_ (
    .A(reset),
    .Y(_202_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(reset),
    .Y(_201_)
  );
  sky130_fd_sc_hd__clkinv_1 _327_ (
    .A(reset),
    .Y(_200_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(reset),
    .Y(_199_)
  );
  sky130_fd_sc_hd__clkinv_1 _329_ (
    .A(reset),
    .Y(_198_)
  );
  sky130_fd_sc_hd__clkinv_1 _330_ (
    .A(reset),
    .Y(_197_)
  );
  sky130_fd_sc_hd__clkinv_1 _331_ (
    .A(reset),
    .Y(_196_)
  );
  sky130_fd_sc_hd__clkinv_1 _332_ (
    .A(reset),
    .Y(_195_)
  );
  sky130_fd_sc_hd__clkinv_1 _333_ (
    .A(reset),
    .Y(_194_)
  );
  sky130_fd_sc_hd__clkinv_1 _334_ (
    .A(reset),
    .Y(_193_)
  );
  sky130_fd_sc_hd__clkinv_1 _335_ (
    .A(reset),
    .Y(_192_)
  );
  sky130_fd_sc_hd__clkinv_1 _336_ (
    .A(reset),
    .Y(_191_)
  );
  sky130_fd_sc_hd__clkinv_1 _337_ (
    .A(reset),
    .Y(_190_)
  );
  sky130_fd_sc_hd__clkinv_1 _338_ (
    .A(reset),
    .Y(_189_)
  );
  sky130_fd_sc_hd__clkinv_1 _339_ (
    .A(reset),
    .Y(_188_)
  );
  sky130_fd_sc_hd__clkinv_1 _340_ (
    .A(reset),
    .Y(_187_)
  );
  sky130_fd_sc_hd__clkinv_1 _341_ (
    .A(reset),
    .Y(_186_)
  );
  sky130_fd_sc_hd__clkinv_1 _342_ (
    .A(reset),
    .Y(_185_)
  );
  sky130_fd_sc_hd__clkinv_1 _343_ (
    .A(reset),
    .Y(_184_)
  );
  sky130_fd_sc_hd__clkinv_1 _344_ (
    .A(reset),
    .Y(_183_)
  );
  sky130_fd_sc_hd__clkinv_1 _345_ (
    .A(reset),
    .Y(_182_)
  );
  sky130_fd_sc_hd__clkinv_1 _346_ (
    .A(reset),
    .Y(_181_)
  );
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(reset),
    .Y(_180_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(reset),
    .Y(_179_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(reset),
    .Y(_178_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(reset),
    .Y(_177_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(reset),
    .Y(_176_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(reset),
    .Y(_175_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(reset),
    .Y(_174_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(reset),
    .Y(_173_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(reset),
    .Y(_172_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(reset),
    .Y(_171_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(reset),
    .Y(_170_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(reset),
    .Y(_169_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(reset),
    .Y(_168_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(reset),
    .Y(_167_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(reset),
    .Y(_166_)
  );
  sky130_fd_sc_hd__clkinv_1 _362_ (
    .A(reset),
    .Y(_165_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(reset),
    .Y(_164_)
  );
  sky130_fd_sc_hd__clkinv_1 _364_ (
    .A(reset),
    .Y(_163_)
  );
  sky130_fd_sc_hd__clkinv_1 _365_ (
    .A(reset),
    .Y(_162_)
  );
  sky130_fd_sc_hd__clkinv_1 _366_ (
    .A(reset),
    .Y(_161_)
  );
  sky130_fd_sc_hd__clkinv_1 _367_ (
    .A(reset),
    .Y(_160_)
  );
  sky130_fd_sc_hd__clkinv_1 _368_ (
    .A(reset),
    .Y(_159_)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(clk),
    .D(\pc_unit.pc [13]),
    .Q(\if_id_reg.pc_out [13]),
    .RESET_B(_177_)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(clk),
    .D(\pc_unit.pc [12]),
    .Q(\if_id_reg.pc_out [12]),
    .RESET_B(_178_)
  );
  sky130_fd_sc_hd__dfrtp_1 _371_ (
    .CLK(clk),
    .D(\pc_unit.pc [11]),
    .Q(\if_id_reg.pc_out [11]),
    .RESET_B(_179_)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(clk),
    .D(\pc_unit.pc [10]),
    .Q(\if_id_reg.pc_out [10]),
    .RESET_B(_180_)
  );
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(clk),
    .D(\pc_unit.pc [9]),
    .Q(\if_id_reg.pc_out [9]),
    .RESET_B(_181_)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(clk),
    .D(\pc_unit.pc [8]),
    .Q(\if_id_reg.pc_out [8]),
    .RESET_B(_182_)
  );
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(clk),
    .D(\pc_unit.pc [7]),
    .Q(\if_id_reg.pc_out [7]),
    .RESET_B(_183_)
  );
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(clk),
    .D(\pc_unit.pc [6]),
    .Q(\if_id_reg.pc_out [6]),
    .RESET_B(_184_)
  );
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(clk),
    .D(\pc_unit.pc [5]),
    .Q(\if_id_reg.pc_out [5]),
    .RESET_B(_185_)
  );
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(clk),
    .D(\pc_unit.pc [4]),
    .Q(\if_id_reg.pc_out [4]),
    .RESET_B(_186_)
  );
  sky130_fd_sc_hd__dfrtp_1 _379_ (
    .CLK(clk),
    .D(\pc_unit.pc [3]),
    .Q(\if_id_reg.pc_out [3]),
    .RESET_B(_187_)
  );
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(clk),
    .D(\pc_unit.pc [2]),
    .Q(\if_id_reg.pc_out [2]),
    .RESET_B(_188_)
  );
  sky130_fd_sc_hd__dfrtp_1 _381_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [31]),
    .Q(\pc_unit.pc [31]),
    .RESET_B(_189_)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [30]),
    .Q(\pc_unit.pc [30]),
    .RESET_B(_190_)
  );
  sky130_fd_sc_hd__dfrtp_1 _383_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [29]),
    .Q(\pc_unit.pc [29]),
    .RESET_B(_191_)
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [28]),
    .Q(\pc_unit.pc [28]),
    .RESET_B(_192_)
  );
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [27]),
    .Q(\pc_unit.pc [27]),
    .RESET_B(_193_)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [26]),
    .Q(\pc_unit.pc [26]),
    .RESET_B(_194_)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [25]),
    .Q(\pc_unit.pc [25]),
    .RESET_B(_195_)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [24]),
    .Q(\pc_unit.pc [24]),
    .RESET_B(_196_)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [23]),
    .Q(\pc_unit.pc [23]),
    .RESET_B(_197_)
  );
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [22]),
    .Q(\pc_unit.pc [22]),
    .RESET_B(_198_)
  );
  sky130_fd_sc_hd__dfrtp_1 _391_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [21]),
    .Q(\pc_unit.pc [21]),
    .RESET_B(_199_)
  );
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [20]),
    .Q(\pc_unit.pc [20]),
    .RESET_B(_200_)
  );
  sky130_fd_sc_hd__dfrtp_1 _393_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [19]),
    .Q(\pc_unit.pc [19]),
    .RESET_B(_201_)
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [18]),
    .Q(\pc_unit.pc [18]),
    .RESET_B(_202_)
  );
  sky130_fd_sc_hd__dfrtp_1 _395_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [17]),
    .Q(\pc_unit.pc [17]),
    .RESET_B(_203_)
  );
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [16]),
    .Q(\pc_unit.pc [16]),
    .RESET_B(_204_)
  );
  sky130_fd_sc_hd__dfrtp_1 _397_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [15]),
    .Q(\pc_unit.pc [15]),
    .RESET_B(_205_)
  );
  sky130_fd_sc_hd__dfrtp_1 _398_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [14]),
    .Q(\pc_unit.pc [14]),
    .RESET_B(_206_)
  );
  sky130_fd_sc_hd__dfrtp_1 _399_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [13]),
    .Q(\pc_unit.pc [13]),
    .RESET_B(_207_)
  );
  sky130_fd_sc_hd__dfrtp_1 _400_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [12]),
    .Q(\pc_unit.pc [12]),
    .RESET_B(_208_)
  );
  sky130_fd_sc_hd__dfrtp_1 _401_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [11]),
    .Q(\pc_unit.pc [11]),
    .RESET_B(_209_)
  );
  sky130_fd_sc_hd__dfrtp_1 _402_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [10]),
    .Q(\pc_unit.pc [10]),
    .RESET_B(_210_)
  );
  sky130_fd_sc_hd__dfrtp_1 _403_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [9]),
    .Q(\pc_unit.pc [9]),
    .RESET_B(_211_)
  );
  sky130_fd_sc_hd__dfrtp_1 _404_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [8]),
    .Q(\pc_unit.pc [8]),
    .RESET_B(_212_)
  );
  sky130_fd_sc_hd__dfrtp_1 _405_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [7]),
    .Q(\pc_unit.pc [7]),
    .RESET_B(_213_)
  );
  sky130_fd_sc_hd__dfrtp_1 _406_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [6]),
    .Q(\pc_unit.pc [6]),
    .RESET_B(_214_)
  );
  sky130_fd_sc_hd__dfrtp_1 _407_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [5]),
    .Q(\pc_unit.pc [5]),
    .RESET_B(_215_)
  );
  sky130_fd_sc_hd__dfrtp_1 _408_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [4]),
    .Q(\pc_unit.pc [4]),
    .RESET_B(_216_)
  );
  sky130_fd_sc_hd__dfrtp_1 _409_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [3]),
    .Q(\pc_unit.pc [3]),
    .RESET_B(_217_)
  );
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(clk),
    .D(\pc_unit.next_pc [2]),
    .Q(\pc_unit.pc [2]),
    .RESET_B(_218_)
  );
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(clk),
    .D(\pc_unit.pc [31]),
    .Q(\if_id_reg.pc_out [31]),
    .RESET_B(_159_)
  );
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(clk),
    .D(\pc_unit.pc [30]),
    .Q(\if_id_reg.pc_out [30]),
    .RESET_B(_160_)
  );
  sky130_fd_sc_hd__dfrtp_1 _413_ (
    .CLK(clk),
    .D(\pc_unit.pc [29]),
    .Q(\if_id_reg.pc_out [29]),
    .RESET_B(_161_)
  );
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(clk),
    .D(\pc_unit.pc [28]),
    .Q(\if_id_reg.pc_out [28]),
    .RESET_B(_162_)
  );
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(clk),
    .D(\pc_unit.pc [27]),
    .Q(\if_id_reg.pc_out [27]),
    .RESET_B(_163_)
  );
  sky130_fd_sc_hd__dfrtp_1 _416_ (
    .CLK(clk),
    .D(\pc_unit.pc [26]),
    .Q(\if_id_reg.pc_out [26]),
    .RESET_B(_164_)
  );
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(clk),
    .D(\pc_unit.pc [25]),
    .Q(\if_id_reg.pc_out [25]),
    .RESET_B(_165_)
  );
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(clk),
    .D(\pc_unit.pc [24]),
    .Q(\if_id_reg.pc_out [24]),
    .RESET_B(_166_)
  );
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(clk),
    .D(\pc_unit.pc [23]),
    .Q(\if_id_reg.pc_out [23]),
    .RESET_B(_167_)
  );
  sky130_fd_sc_hd__dfrtp_1 _420_ (
    .CLK(clk),
    .D(\pc_unit.pc [22]),
    .Q(\if_id_reg.pc_out [22]),
    .RESET_B(_168_)
  );
  sky130_fd_sc_hd__dfrtp_1 _421_ (
    .CLK(clk),
    .D(\pc_unit.pc [21]),
    .Q(\if_id_reg.pc_out [21]),
    .RESET_B(_169_)
  );
  sky130_fd_sc_hd__dfrtp_1 _422_ (
    .CLK(clk),
    .D(\pc_unit.pc [20]),
    .Q(\if_id_reg.pc_out [20]),
    .RESET_B(_170_)
  );
  sky130_fd_sc_hd__dfrtp_1 _423_ (
    .CLK(clk),
    .D(\pc_unit.pc [19]),
    .Q(\if_id_reg.pc_out [19]),
    .RESET_B(_171_)
  );
  sky130_fd_sc_hd__dfrtp_1 _424_ (
    .CLK(clk),
    .D(\pc_unit.pc [18]),
    .Q(\if_id_reg.pc_out [18]),
    .RESET_B(_172_)
  );
  sky130_fd_sc_hd__dfrtp_1 _425_ (
    .CLK(clk),
    .D(\pc_unit.pc [17]),
    .Q(\if_id_reg.pc_out [17]),
    .RESET_B(_173_)
  );
  sky130_fd_sc_hd__dfrtp_1 _426_ (
    .CLK(clk),
    .D(\pc_unit.pc [16]),
    .Q(\if_id_reg.pc_out [16]),
    .RESET_B(_174_)
  );
  sky130_fd_sc_hd__dfrtp_1 _427_ (
    .CLK(clk),
    .D(\pc_unit.pc [15]),
    .Q(\if_id_reg.pc_out [15]),
    .RESET_B(_175_)
  );
  sky130_fd_sc_hd__dfrtp_1 _428_ (
    .CLK(clk),
    .D(\pc_unit.pc [14]),
    .Q(\if_id_reg.pc_out [14]),
    .RESET_B(_176_)
  );
  assign \alu_control_unit.alu_ctrl  = 4'h0;
  assign \alu_control_unit.alu_op  = 2'h0;
  assign \alu_control_unit.funct3  = 3'h0;
  assign \alu_control_unit.funct7  = 7'h00;
  assign alu_ctrl = 4'h0;
  assign alu_input_a = { \alu_unit.a [31], 31'h00000000 };
  assign alu_input_b = { \alu_unit.a [31], 31'h00000000 };
  assign alu_input_b_forwarded = { \alu_unit.a [31], 31'h00000000 };
  assign alu_op = 2'h0;
  assign alu_result = 32'd0;
  assign alu_src = 1'h0;
  assign \alu_unit.a [30:0] = 31'h00000000;
  assign \alu_unit.alu_ctrl  = 4'h0;
  assign \alu_unit.b  = { \alu_unit.a [31], 31'h00000000 };
  assign \alu_unit.result  = 32'd0;
  assign branch = 1'h0;
  assign branch_taken = 1'h0;
  assign branch_target = { \id_ex_reg.pc_out [31:2], 2'h0 };
  assign \control_unit.alu_op  = 2'h0;
  assign \control_unit.alu_src  = 1'h0;
  assign \control_unit.branch  = 1'h0;
  assign \control_unit.jump  = 1'h0;
  assign \control_unit.mem_read  = 1'h0;
  assign \control_unit.mem_to_reg  = 1'h0;
  assign \control_unit.mem_write  = 1'h0;
  assign \control_unit.opcode  = 7'h00;
  assign \control_unit.reg_write  = 1'h0;
  assign \control_unit.wb_pc4  = 1'h0;
  assign \data_mem.address  = 32'd0;
  assign \data_mem.clk  = clk;
  assign \data_mem.i  = 32'd256;
  assign \data_mem.mem_read  = 1'h0;
  assign \data_mem.mem_write  = 1'h0;
  assign \data_mem.memory[0]  = 32'd0;
  assign \data_mem.memory[100]  = 32'd0;
  assign \data_mem.memory[101]  = 32'd0;
  assign \data_mem.memory[102]  = 32'd0;
  assign \data_mem.memory[103]  = 32'd0;
  assign \data_mem.memory[104]  = 32'd0;
  assign \data_mem.memory[105]  = 32'd0;
  assign \data_mem.memory[106]  = 32'd0;
  assign \data_mem.memory[107]  = 32'd0;
  assign \data_mem.memory[108]  = 32'd0;
  assign \data_mem.memory[109]  = 32'd0;
  assign \data_mem.memory[10]  = 32'd0;
  assign \data_mem.memory[110]  = 32'd0;
  assign \data_mem.memory[111]  = 32'd0;
  assign \data_mem.memory[112]  = 32'd0;
  assign \data_mem.memory[113]  = 32'd0;
  assign \data_mem.memory[114]  = 32'd0;
  assign \data_mem.memory[115]  = 32'd0;
  assign \data_mem.memory[116]  = 32'd0;
  assign \data_mem.memory[117]  = 32'd0;
  assign \data_mem.memory[118]  = 32'd0;
  assign \data_mem.memory[119]  = 32'd0;
  assign \data_mem.memory[11]  = 32'd0;
  assign \data_mem.memory[120]  = 32'd0;
  assign \data_mem.memory[121]  = 32'd0;
  assign \data_mem.memory[122]  = 32'd0;
  assign \data_mem.memory[123]  = 32'd0;
  assign \data_mem.memory[124]  = 32'd0;
  assign \data_mem.memory[125]  = 32'd0;
  assign \data_mem.memory[126]  = 32'd0;
  assign \data_mem.memory[127]  = 32'd0;
  assign \data_mem.memory[128]  = 32'd0;
  assign \data_mem.memory[129]  = 32'd0;
  assign \data_mem.memory[12]  = 32'd0;
  assign \data_mem.memory[130]  = 32'd0;
  assign \data_mem.memory[131]  = 32'd0;
  assign \data_mem.memory[132]  = 32'd0;
  assign \data_mem.memory[133]  = 32'd0;
  assign \data_mem.memory[134]  = 32'd0;
  assign \data_mem.memory[135]  = 32'd0;
  assign \data_mem.memory[136]  = 32'd0;
  assign \data_mem.memory[137]  = 32'd0;
  assign \data_mem.memory[138]  = 32'd0;
  assign \data_mem.memory[139]  = 32'd0;
  assign \data_mem.memory[13]  = 32'd0;
  assign \data_mem.memory[140]  = 32'd0;
  assign \data_mem.memory[141]  = 32'd0;
  assign \data_mem.memory[142]  = 32'd0;
  assign \data_mem.memory[143]  = 32'd0;
  assign \data_mem.memory[144]  = 32'd0;
  assign \data_mem.memory[145]  = 32'd0;
  assign \data_mem.memory[146]  = 32'd0;
  assign \data_mem.memory[147]  = 32'd0;
  assign \data_mem.memory[148]  = 32'd0;
  assign \data_mem.memory[149]  = 32'd0;
  assign \data_mem.memory[14]  = 32'd0;
  assign \data_mem.memory[150]  = 32'd0;
  assign \data_mem.memory[151]  = 32'd0;
  assign \data_mem.memory[152]  = 32'd0;
  assign \data_mem.memory[153]  = 32'd0;
  assign \data_mem.memory[154]  = 32'd0;
  assign \data_mem.memory[155]  = 32'd0;
  assign \data_mem.memory[156]  = 32'd0;
  assign \data_mem.memory[157]  = 32'd0;
  assign \data_mem.memory[158]  = 32'd0;
  assign \data_mem.memory[159]  = 32'd0;
  assign \data_mem.memory[15]  = 32'd0;
  assign \data_mem.memory[160]  = 32'd0;
  assign \data_mem.memory[161]  = 32'd0;
  assign \data_mem.memory[162]  = 32'd0;
  assign \data_mem.memory[163]  = 32'd0;
  assign \data_mem.memory[164]  = 32'd0;
  assign \data_mem.memory[165]  = 32'd0;
  assign \data_mem.memory[166]  = 32'd0;
  assign \data_mem.memory[167]  = 32'd0;
  assign \data_mem.memory[168]  = 32'd0;
  assign \data_mem.memory[169]  = 32'd0;
  assign \data_mem.memory[16]  = 32'd0;
  assign \data_mem.memory[170]  = 32'd0;
  assign \data_mem.memory[171]  = 32'd0;
  assign \data_mem.memory[172]  = 32'd0;
  assign \data_mem.memory[173]  = 32'd0;
  assign \data_mem.memory[174]  = 32'd0;
  assign \data_mem.memory[175]  = 32'd0;
  assign \data_mem.memory[176]  = 32'd0;
  assign \data_mem.memory[177]  = 32'd0;
  assign \data_mem.memory[178]  = 32'd0;
  assign \data_mem.memory[179]  = 32'd0;
  assign \data_mem.memory[17]  = 32'd0;
  assign \data_mem.memory[180]  = 32'd0;
  assign \data_mem.memory[181]  = 32'd0;
  assign \data_mem.memory[182]  = 32'd0;
  assign \data_mem.memory[183]  = 32'd0;
  assign \data_mem.memory[184]  = 32'd0;
  assign \data_mem.memory[185]  = 32'd0;
  assign \data_mem.memory[186]  = 32'd0;
  assign \data_mem.memory[187]  = 32'd0;
  assign \data_mem.memory[188]  = 32'd0;
  assign \data_mem.memory[189]  = 32'd0;
  assign \data_mem.memory[18]  = 32'd0;
  assign \data_mem.memory[190]  = 32'd0;
  assign \data_mem.memory[191]  = 32'd0;
  assign \data_mem.memory[192]  = 32'd0;
  assign \data_mem.memory[193]  = 32'd0;
  assign \data_mem.memory[194]  = 32'd0;
  assign \data_mem.memory[195]  = 32'd0;
  assign \data_mem.memory[196]  = 32'd0;
  assign \data_mem.memory[197]  = 32'd0;
  assign \data_mem.memory[198]  = 32'd0;
  assign \data_mem.memory[199]  = 32'd0;
  assign \data_mem.memory[19]  = 32'd0;
  assign \data_mem.memory[1]  = 32'd0;
  assign \data_mem.memory[200]  = 32'd0;
  assign \data_mem.memory[201]  = 32'd0;
  assign \data_mem.memory[202]  = 32'd0;
  assign \data_mem.memory[203]  = 32'd0;
  assign \data_mem.memory[204]  = 32'd0;
  assign \data_mem.memory[205]  = 32'd0;
  assign \data_mem.memory[206]  = 32'd0;
  assign \data_mem.memory[207]  = 32'd0;
  assign \data_mem.memory[208]  = 32'd0;
  assign \data_mem.memory[209]  = 32'd0;
  assign \data_mem.memory[20]  = 32'd0;
  assign \data_mem.memory[210]  = 32'd0;
  assign \data_mem.memory[211]  = 32'd0;
  assign \data_mem.memory[212]  = 32'd0;
  assign \data_mem.memory[213]  = 32'd0;
  assign \data_mem.memory[214]  = 32'd0;
  assign \data_mem.memory[215]  = 32'd0;
  assign \data_mem.memory[216]  = 32'd0;
  assign \data_mem.memory[217]  = 32'd0;
  assign \data_mem.memory[218]  = 32'd0;
  assign \data_mem.memory[219]  = 32'd0;
  assign \data_mem.memory[21]  = 32'd0;
  assign \data_mem.memory[220]  = 32'd0;
  assign \data_mem.memory[221]  = 32'd0;
  assign \data_mem.memory[222]  = 32'd0;
  assign \data_mem.memory[223]  = 32'd0;
  assign \data_mem.memory[224]  = 32'd0;
  assign \data_mem.memory[225]  = 32'd0;
  assign \data_mem.memory[226]  = 32'd0;
  assign \data_mem.memory[227]  = 32'd0;
  assign \data_mem.memory[228]  = 32'd0;
  assign \data_mem.memory[229]  = 32'd0;
  assign \data_mem.memory[22]  = 32'd0;
  assign \data_mem.memory[230]  = 32'd0;
  assign \data_mem.memory[231]  = 32'd0;
  assign \data_mem.memory[232]  = 32'd0;
  assign \data_mem.memory[233]  = 32'd0;
  assign \data_mem.memory[234]  = 32'd0;
  assign \data_mem.memory[235]  = 32'd0;
  assign \data_mem.memory[236]  = 32'd0;
  assign \data_mem.memory[237]  = 32'd0;
  assign \data_mem.memory[238]  = 32'd0;
  assign \data_mem.memory[239]  = 32'd0;
  assign \data_mem.memory[23]  = 32'd0;
  assign \data_mem.memory[240]  = 32'd0;
  assign \data_mem.memory[241]  = 32'd0;
  assign \data_mem.memory[242]  = 32'd0;
  assign \data_mem.memory[243]  = 32'd0;
  assign \data_mem.memory[244]  = 32'd0;
  assign \data_mem.memory[245]  = 32'd0;
  assign \data_mem.memory[246]  = 32'd0;
  assign \data_mem.memory[247]  = 32'd0;
  assign \data_mem.memory[248]  = 32'd0;
  assign \data_mem.memory[249]  = 32'd0;
  assign \data_mem.memory[24]  = 32'd0;
  assign \data_mem.memory[250]  = 32'd0;
  assign \data_mem.memory[251]  = 32'd0;
  assign \data_mem.memory[252]  = 32'd0;
  assign \data_mem.memory[253]  = 32'd0;
  assign \data_mem.memory[254]  = 32'd0;
  assign \data_mem.memory[255]  = 32'd0;
  assign \data_mem.memory[25]  = 32'd0;
  assign \data_mem.memory[26]  = 32'd0;
  assign \data_mem.memory[27]  = 32'd0;
  assign \data_mem.memory[28]  = 32'd0;
  assign \data_mem.memory[29]  = 32'd0;
  assign \data_mem.memory[2]  = 32'd0;
  assign \data_mem.memory[30]  = 32'd0;
  assign \data_mem.memory[31]  = 32'd0;
  assign \data_mem.memory[32]  = 32'd0;
  assign \data_mem.memory[33]  = 32'd0;
  assign \data_mem.memory[34]  = 32'd0;
  assign \data_mem.memory[35]  = 32'd0;
  assign \data_mem.memory[36]  = 32'd0;
  assign \data_mem.memory[37]  = 32'd0;
  assign \data_mem.memory[38]  = 32'd0;
  assign \data_mem.memory[39]  = 32'd0;
  assign \data_mem.memory[3]  = 32'd0;
  assign \data_mem.memory[40]  = 32'd0;
  assign \data_mem.memory[41]  = 32'd0;
  assign \data_mem.memory[42]  = 32'd0;
  assign \data_mem.memory[43]  = 32'd0;
  assign \data_mem.memory[44]  = 32'd0;
  assign \data_mem.memory[45]  = 32'd0;
  assign \data_mem.memory[46]  = 32'd0;
  assign \data_mem.memory[47]  = 32'd0;
  assign \data_mem.memory[48]  = 32'd0;
  assign \data_mem.memory[49]  = 32'd0;
  assign \data_mem.memory[4]  = 32'd0;
  assign \data_mem.memory[50]  = 32'd0;
  assign \data_mem.memory[51]  = 32'd0;
  assign \data_mem.memory[52]  = 32'd0;
  assign \data_mem.memory[53]  = 32'd0;
  assign \data_mem.memory[54]  = 32'd0;
  assign \data_mem.memory[55]  = 32'd0;
  assign \data_mem.memory[56]  = 32'd0;
  assign \data_mem.memory[57]  = 32'd0;
  assign \data_mem.memory[58]  = 32'd0;
  assign \data_mem.memory[59]  = 32'd0;
  assign \data_mem.memory[5]  = 32'd0;
  assign \data_mem.memory[60]  = 32'd0;
  assign \data_mem.memory[61]  = 32'd0;
  assign \data_mem.memory[62]  = 32'd0;
  assign \data_mem.memory[63]  = 32'd0;
  assign \data_mem.memory[64]  = 32'd0;
  assign \data_mem.memory[65]  = 32'd0;
  assign \data_mem.memory[66]  = 32'd0;
  assign \data_mem.memory[67]  = 32'd0;
  assign \data_mem.memory[68]  = 32'd0;
  assign \data_mem.memory[69]  = 32'd0;
  assign \data_mem.memory[6]  = 32'd0;
  assign \data_mem.memory[70]  = 32'd0;
  assign \data_mem.memory[71]  = 32'd0;
  assign \data_mem.memory[72]  = 32'd0;
  assign \data_mem.memory[73]  = 32'd0;
  assign \data_mem.memory[74]  = 32'd0;
  assign \data_mem.memory[75]  = 32'd0;
  assign \data_mem.memory[76]  = 32'd0;
  assign \data_mem.memory[77]  = 32'd0;
  assign \data_mem.memory[78]  = 32'd0;
  assign \data_mem.memory[79]  = 32'd0;
  assign \data_mem.memory[7]  = 32'd0;
  assign \data_mem.memory[80]  = 32'd0;
  assign \data_mem.memory[81]  = 32'd0;
  assign \data_mem.memory[82]  = 32'd0;
  assign \data_mem.memory[83]  = 32'd0;
  assign \data_mem.memory[84]  = 32'd0;
  assign \data_mem.memory[85]  = 32'd0;
  assign \data_mem.memory[86]  = 32'd0;
  assign \data_mem.memory[87]  = 32'd0;
  assign \data_mem.memory[88]  = 32'd0;
  assign \data_mem.memory[89]  = 32'd0;
  assign \data_mem.memory[8]  = 32'd0;
  assign \data_mem.memory[90]  = 32'd0;
  assign \data_mem.memory[91]  = 32'd0;
  assign \data_mem.memory[92]  = 32'd0;
  assign \data_mem.memory[93]  = 32'd0;
  assign \data_mem.memory[94]  = 32'd0;
  assign \data_mem.memory[95]  = 32'd0;
  assign \data_mem.memory[96]  = 32'd0;
  assign \data_mem.memory[97]  = 32'd0;
  assign \data_mem.memory[98]  = 32'd0;
  assign \data_mem.memory[99]  = 32'd0;
  assign \data_mem.memory[9]  = 32'd0;
  assign \data_mem.write_data [30:0] = 31'h00000000;
  assign debug_pc = { \if_id_reg.pc_out [31:2], 2'h0 };
  assign debug_reg_addr = 5'h00;
  assign debug_reg_data = 32'd0;
  assign debug_reg_write = 1'h0;
  assign \decoder_unit.funct3  = 3'h0;
  assign \decoder_unit.funct7  = 7'h00;
  assign \decoder_unit.instruction  = 32'd0;
  assign \decoder_unit.opcode  = 7'h00;
  assign \decoder_unit.rd  = 5'h00;
  assign \decoder_unit.rs1  = 5'h00;
  assign \decoder_unit.rs2  = 5'h00;
  assign ex_mem_alu_result = 32'd0;
  assign ex_mem_mem_read = 1'h0;
  assign ex_mem_mem_to_reg = 1'h0;
  assign ex_mem_mem_write = 1'h0;
  assign ex_mem_pc_plus4 = { \ex_mem_reg.pc_plus4_out [31:1], \ex_mem_reg.pc_plus4_out [1] };
  assign ex_mem_rd = 5'h00;
  assign \ex_mem_reg.alu_result_in  = 32'd0;
  assign \ex_mem_reg.alu_result_out  = 32'd0;
  assign \ex_mem_reg.branch_in  = 1'h0;
  assign \ex_mem_reg.clk  = clk;
  assign \ex_mem_reg.jump_in  = 1'h0;
  assign \ex_mem_reg.mem_read_in  = 1'h0;
  assign \ex_mem_reg.mem_read_out  = 1'h0;
  assign \ex_mem_reg.mem_to_reg_in  = 1'h0;
  assign \ex_mem_reg.mem_to_reg_out  = 1'h0;
  assign \ex_mem_reg.mem_write_in  = 1'h0;
  assign \ex_mem_reg.mem_write_out  = 1'h0;
  assign \ex_mem_reg.pc_plus4_in [1:0] = 2'h0;
  assign \ex_mem_reg.pc_plus4_out [0] = \ex_mem_reg.pc_plus4_out [1];
  assign \ex_mem_reg.rd_in  = 5'h00;
  assign \ex_mem_reg.rd_out  = 5'h00;
  assign \ex_mem_reg.reg_write_in  = 1'h0;
  assign \ex_mem_reg.reg_write_out  = 1'h0;
  assign \ex_mem_reg.reset  = reset;
  assign \ex_mem_reg.wb_pc4_in  = 1'h0;
  assign \ex_mem_reg.wb_pc4_out  = 1'h0;
  assign \ex_mem_reg.write_data_in  = { \alu_unit.a [31], 31'h00000000 };
  assign \ex_mem_reg.write_data_out  = { \data_mem.write_data [31], 31'h00000000 };
  assign ex_mem_reg_write = 1'h0;
  assign ex_mem_rs2_data = { \data_mem.write_data [31], 31'h00000000 };
  assign ex_mem_wb_pc4 = 1'h0;
  assign forward_a = 2'h0;
  assign forward_b = 2'h0;
  assign \forwarding_unit_inst.ex_mem_rd  = 5'h00;
  assign \forwarding_unit_inst.ex_mem_reg_write  = 1'h0;
  assign \forwarding_unit_inst.forward_a  = 2'h0;
  assign \forwarding_unit_inst.forward_b  = 2'h0;
  assign \forwarding_unit_inst.id_ex_rs1  = 5'h00;
  assign \forwarding_unit_inst.id_ex_rs2  = 5'h00;
  assign \forwarding_unit_inst.mem_wb_rd  = 5'h00;
  assign \forwarding_unit_inst.mem_wb_reg_write  = 1'h0;
  assign funct3 = 3'h0;
  assign funct7 = 7'h00;
  assign \hazard_unit.control_mux_select  = 1'h0;
  assign \hazard_unit.id_ex_memread  = 1'h0;
  assign \hazard_unit.id_ex_rd  = 5'h00;
  assign \hazard_unit.if_id_rs1  = 5'h00;
  assign \hazard_unit.if_id_rs2  = 5'h00;
  assign \hazard_unit.if_id_write  = 1'h1;
  assign \hazard_unit.pc_write  = 1'h1;
  assign id_ex_alu_op = 2'h0;
  assign id_ex_alu_src = 1'h0;
  assign id_ex_branch = 1'h0;
  assign id_ex_branch_flush = 1'h0;
  assign id_ex_flush = 1'h0;
  assign id_ex_funct3 = 3'h0;
  assign id_ex_funct7 = 7'h00;
  assign id_ex_imm = 32'd0;
  assign id_ex_jump = 1'h0;
  assign id_ex_mem_read = 1'h0;
  assign id_ex_mem_to_reg = 1'h0;
  assign id_ex_mem_write = 1'h0;
  assign id_ex_opcode = 7'h00;
  assign id_ex_pc = { \id_ex_reg.pc_out [31:2], 2'h0 };
  assign id_ex_rd = 5'h00;
  assign \id_ex_reg.alu_op_in  = 2'h0;
  assign \id_ex_reg.alu_op_out  = 2'h0;
  assign \id_ex_reg.alu_src_in  = 1'h0;
  assign \id_ex_reg.alu_src_out  = 1'h0;
  assign \id_ex_reg.branch_in  = 1'h0;
  assign \id_ex_reg.branch_out  = 1'h0;
  assign \id_ex_reg.clk  = clk;
  assign \id_ex_reg.funct3_in  = 3'h0;
  assign \id_ex_reg.funct3_out  = 3'h0;
  assign \id_ex_reg.funct7_in  = 7'h00;
  assign \id_ex_reg.funct7_out  = 7'h00;
  assign \id_ex_reg.imm_in  = 32'd0;
  assign \id_ex_reg.imm_out  = 32'd0;
  assign \id_ex_reg.jump_in  = 1'h0;
  assign \id_ex_reg.jump_out  = 1'h0;
  assign \id_ex_reg.mem_read_in  = 1'h0;
  assign \id_ex_reg.mem_read_out  = 1'h0;
  assign \id_ex_reg.mem_to_reg_in  = 1'h0;
  assign \id_ex_reg.mem_to_reg_out  = 1'h0;
  assign \id_ex_reg.mem_write_in  = 1'h0;
  assign \id_ex_reg.mem_write_out  = 1'h0;
  assign \id_ex_reg.opcode_in  = 7'h00;
  assign \id_ex_reg.opcode_out  = 7'h00;
  assign \id_ex_reg.pc_in  = { \if_id_reg.pc_out [31:2], 2'h0 };
  assign \id_ex_reg.pc_out [1:0] = 2'h0;
  assign \id_ex_reg.rd_in  = 5'h00;
  assign \id_ex_reg.rd_out  = 5'h00;
  assign \id_ex_reg.reg_write_in  = 1'h0;
  assign \id_ex_reg.reg_write_out  = 1'h0;
  assign \id_ex_reg.reset  = reset;
  assign \id_ex_reg.rs1_data_in  = 32'd0;
  assign \id_ex_reg.rs1_data_out  = 32'd0;
  assign \id_ex_reg.rs1_in  = 5'h00;
  assign \id_ex_reg.rs1_out  = 5'h00;
  assign \id_ex_reg.rs2_data_in  = 32'd0;
  assign \id_ex_reg.rs2_data_out  = 32'd0;
  assign \id_ex_reg.rs2_in  = 5'h00;
  assign \id_ex_reg.rs2_out  = 5'h00;
  assign \id_ex_reg.wb_pc4_in  = 1'h0;
  assign \id_ex_reg.wb_pc4_out  = 1'h0;
  assign id_ex_reg_write = 1'h0;
  assign id_ex_rs1 = 5'h00;
  assign id_ex_rs1_data = 32'd0;
  assign id_ex_rs2 = 5'h00;
  assign id_ex_rs2_data = 32'd0;
  assign id_ex_wb_pc4 = 1'h0;
  assign if_id_flush = 1'h0;
  assign if_id_instruction = 32'd0;
  assign if_id_pc = { \if_id_reg.pc_out [31:2], 2'h0 };
  assign \if_id_reg.clk  = clk;
  assign \if_id_reg.flush  = 1'h0;
  assign \if_id_reg.instruction_in  = 32'hxxxxxxxx;
  assign \if_id_reg.instruction_out  = 32'd0;
  assign \if_id_reg.pc_in  = { \pc_unit.pc [31:2], 2'h0 };
  assign \if_id_reg.pc_out [1:0] = 2'h0;
  assign \if_id_reg.reset  = reset;
  assign \if_id_reg.write_enable  = 1'h1;
  assign if_id_write = 1'h1;
  assign \imem.address  = { \pc_unit.pc [31:2], 2'h0 };
  assign \imem.instruction  = 32'hxxxxxxxx;
  assign imm_out = 32'd0;
  assign \imm_unit.imm_out  = 32'd0;
  assign \imm_unit.instruction  = 32'd0;
  assign instruction = 32'hxxxxxxxx;
  assign jalr_target[0] = 1'h0;
  assign jump = 1'h0;
  assign jump_taken = 1'h0;
  assign jump_target = { \id_ex_reg.pc_out [31:2], 2'h0 };
  assign mem_read = 1'h0;
  assign mem_to_reg = 1'h0;
  assign mem_wb_alu_result = 32'd0;
  assign mem_wb_mem_data = 32'd0;
  assign mem_wb_mem_to_reg = 1'h0;
  assign mem_wb_pc_plus4 = { \mem_wb_reg.pc_plus4_out [31:1], \mem_wb_reg.pc_plus4_out [1] };
  assign mem_wb_rd = 5'h00;
  assign \mem_wb_reg.alu_result_in  = 32'd0;
  assign \mem_wb_reg.alu_result_out  = 32'd0;
  assign \mem_wb_reg.clk  = clk;
  assign \mem_wb_reg.mem_data_out  = 32'd0;
  assign \mem_wb_reg.mem_to_reg_in  = 1'h0;
  assign \mem_wb_reg.mem_to_reg_out  = 1'h0;
  assign \mem_wb_reg.pc_plus4_in  = { \ex_mem_reg.pc_plus4_out [31:1], \ex_mem_reg.pc_plus4_out [1] };
  assign \mem_wb_reg.pc_plus4_out [0] = \mem_wb_reg.pc_plus4_out [1];
  assign \mem_wb_reg.rd_in  = 5'h00;
  assign \mem_wb_reg.rd_out  = 5'h00;
  assign \mem_wb_reg.reg_write_in  = 1'h0;
  assign \mem_wb_reg.reg_write_out  = 1'h0;
  assign \mem_wb_reg.reset  = reset;
  assign \mem_wb_reg.wb_pc4_in  = 1'h0;
  assign \mem_wb_reg.wb_pc4_out  = 1'h0;
  assign mem_wb_reg_write = 1'h0;
  assign mem_wb_wb_pc4 = 1'h0;
  assign mem_write = 1'h0;
  assign next_pc = { \pc_unit.next_pc [31:2], 2'hx };
  assign opcode = 7'h00;
  assign pc_plus4 = { \pc_unit.next_pc [31:2], 2'h0 };
  assign \pc_unit.clk  = clk;
  assign \pc_unit.next_pc [1:0] = 2'hx;
  assign \pc_unit.pc [1:0] = 2'h0;
  assign \pc_unit.pc_write  = 1'h1;
  assign \pc_unit.reset  = reset;
  assign pc_value = { \pc_unit.pc [31:2], 2'h0 };
  assign pc_write = 1'h1;
  assign rd = 5'h00;
  assign reg_write = 1'h0;
  assign \regfile_unit.clk  = clk;
  assign \regfile_unit.i  = 32'd32;
  assign \regfile_unit.rd_addr  = 5'h00;
  assign \regfile_unit.rd_data  = 32'd0;
  assign \regfile_unit.reg_write  = 1'h0;
  assign \regfile_unit.regfile[10]  = 32'd0;
  assign \regfile_unit.regfile[11]  = 32'd0;
  assign \regfile_unit.regfile[12]  = 32'd0;
  assign \regfile_unit.regfile[13]  = 32'd0;
  assign \regfile_unit.regfile[14]  = 32'd0;
  assign \regfile_unit.regfile[15]  = 32'd0;
  assign \regfile_unit.regfile[16]  = 32'd0;
  assign \regfile_unit.regfile[17]  = 32'd0;
  assign \regfile_unit.regfile[18]  = 32'd0;
  assign \regfile_unit.regfile[19]  = 32'd0;
  assign \regfile_unit.regfile[1]  = 32'd0;
  assign \regfile_unit.regfile[20]  = 32'd0;
  assign \regfile_unit.regfile[21]  = 32'd0;
  assign \regfile_unit.regfile[22]  = 32'd0;
  assign \regfile_unit.regfile[23]  = 32'd0;
  assign \regfile_unit.regfile[24]  = 32'd0;
  assign \regfile_unit.regfile[25]  = 32'd0;
  assign \regfile_unit.regfile[26]  = 32'd0;
  assign \regfile_unit.regfile[27]  = 32'd0;
  assign \regfile_unit.regfile[28]  = 32'd0;
  assign \regfile_unit.regfile[29]  = 32'd0;
  assign \regfile_unit.regfile[2]  = 32'd0;
  assign \regfile_unit.regfile[30]  = 32'd0;
  assign \regfile_unit.regfile[3]  = 32'd0;
  assign \regfile_unit.regfile[4]  = 32'd0;
  assign \regfile_unit.regfile[5]  = 32'd0;
  assign \regfile_unit.regfile[6]  = 32'd0;
  assign \regfile_unit.regfile[7]  = 32'd0;
  assign \regfile_unit.regfile[8]  = 32'd0;
  assign \regfile_unit.regfile[9]  = 32'd0;
  assign \regfile_unit.rs1_addr  = 5'h00;
  assign \regfile_unit.rs1_data  = 32'd0;
  assign \regfile_unit.rs2_addr  = 5'h00;
  assign \regfile_unit.rs2_data  = 32'd0;
  assign rs1 = 5'h00;
  assign rs1_data = 32'd0;
  assign rs2 = 5'h00;
  assign rs2_data = 32'd0;
  assign store_data_forwarded = { \alu_unit.a [31], 31'h00000000 };
  assign wb_pc4 = 1'h0;
  assign writeback_data = 32'd0;
endmodule
